version: '3'

services:

    db:
        image: mysql:8
        ports:
            - "3306:3306"
        volumes:
            - ./mysqldump:/docker-entrypoint-initdb.d
        environment:
            MYSQL_DATABASE: db
            MYSQL_USER: username
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: rootpassword
    
    web:
        build:
            context: .
            dockerfile: docker/webapi/Dockerfile
        image: flaskrestx-webapi
        ports:
        - "8080:80"
